# Generated by Django 2.1.5 on 2019-06-08 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorite_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='logs',
        ),
        migrations.AddField(
            model_name='audit',
            name='action_flag',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='models_objects',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
